//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheques
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ConceptoPago
    {
        public int Id { get; set; }
        [StringLength(50)]
        [Required]
        [Display(Name = "Descripción Para el Cheque")]
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
    }
}
