//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheques
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.RegistroSolicitudCheque = new HashSet<RegistroSolicitudCheque>();
            this.RegistroSolicitudCheque1 = new HashSet<RegistroSolicitudCheque>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string TipoPersona { get; set; }
        public string Identificacion { get; set; }
        public decimal Balance { get; set; }
        public int CuentaContableProveedor { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroSolicitudCheque> RegistroSolicitudCheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroSolicitudCheque> RegistroSolicitudCheque1 { get; set; }
    }
}
