//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheques
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.RegistroSolicitudCheque = new HashSet<RegistroSolicitudCheque>();
            this.RegistroSolicitudCheque1 = new HashSet<RegistroSolicitudCheque>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string TipoPersona { get; set; }
        public string Identificacion { get; set; }
        public decimal Balance { get; set; }
        public int CuentaContableProveedor { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroSolicitudCheque> RegistroSolicitudCheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroSolicitudCheque> RegistroSolicitudCheque1 { get; set; }
    }
}
