//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheques
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroSolicitudCheque
    {
        public int Id { get; set; }
        public int NumeroSolicitud { get; set; }
        public int IDProveedor { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Estado { get; set; }
        public int CuentaContableProveedor { get; set; }
        public int CuentaContableInterna { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        public virtual Proveedores Proveedores1 { get; set; }
    }
}
